Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - Appraisals
    - spec/dummy/bin/rake
    - spec/dummy/bin/rails
    - spec/dummy/bin/spring
    - gemfiles/vendor/**/*
